name: sparse-tokens
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - numpy
  - scikit-learn
  - wandb
  - pytorch=2.1
  - torchvision=0.16
  - pytorch-cuda=11.8
  - pip:
    - torchshow
    - python-sensors
    - patchify