#!/bin/bash

#SBATCH --job-name=test
#SBATCH --partition=test
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --output=run.out
#SBATCH --time=0:10:00

conda run -n sparse-tokens python main.py -t r -m 100 -s 32 -p 16 -k 8