#!/bin/bash

#SBATCH --job-name=run_tokens
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gpus-per-node=2
#SBATCH --output=run_tokens.out
#SBATCH --time=0:10:00

source /sw/languages/anaconda/anaconda.3.9.13-2022-torch-cuda-11.7.0/etc/profile.d/conda.sh
conda activate sparse-tokens
python tokens.py -t r -m 100 -s 32 -p 16 -k 8 --output r_m_100_s_32_p_16_k_8