#!/bin/bash

#SBATCH --job-name=CIFAR10
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gpus-per-node=2
#SBATCH --output=out/run_train_r_m_100_s_32_p_16_k_8.out
#SBATCH --time=12:00:00

source /sw/languages/anaconda/anaconda.3.9.13-2022-torch-cuda-11.7.0/etc/profile.d/conda.sh
conda activate sparse-tokens

# Oracle
#torchrun --nproc_per_node=2 train.py\
#    --model vit_b_16 --epochs 100 --batch-size 64 --opt adamw --lr 0.003 --wd 0.3\
#    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30\
#    --lr-warmup-decay 0.033 --amp --label-smoothing 0.11 --clip-grad-norm 1 --model-ema\
#    --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# r_m_100_s_32_p_16_k_8
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_vit_b_16 --token-mask r_m_100_s_32_p_16_k_8 --epochs 100 --batch-size 64\
    --opt adamw --lr 0.003 --wd 0.3 --lr-scheduler cosineannealinglr --lr-warmup-method linear\
    --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp --label-smoothing 0.11 --clip-grad-norm 1\
    --model-ema --device cuda --print-freq 100 --log-freq 10 --output-dir ''
