#!/bin/bash

#SBATCH --job-name=CIFAR10
#SBATCH --partition=gpu_veryshort
#SBATCH --nodes=1
#SBATCH --gpus-per-node=2
#SBATCH --output=out/%j.out
#SBATCH --time=0:10:00

source /sw/languages/anaconda/anaconda.3.9.13-2022-torch-cuda-11.7.0/etc/profile.d/conda.sh
conda activate sparse-tokens

# batch_random_k_0_32
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 0 --random-tokens 32 --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_random_k_0_16
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 0 --random-tokens 16 --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_random_k_0_8
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 0 --random-tokens 8 --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_r_b_Identity_m_128_s_128_p_4_k_16_16_frequency
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 16 --random-tokens 16 --strategy frequency --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_r_b_Identity_m_128_s_128_p_4_k_16_16_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 16 --random-tokens 16 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_r_b_Identity_m_128_s_128_p_4_k_8_8_frequency
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 8 --random-tokens 8 --strategy frequency --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_r_b_Identity_m_128_s_128_p_4_k_8_8_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 8 --random-tokens 8 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_r_b_Identity_m_128_s_128_p_4_k_4_4_frequency
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 4 --random-tokens 4 --strategy frequency --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_r_b_Identity_m_128_s_128_p_4_k_4_4_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'r' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 4 --random-tokens 4 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_16_16_frequency
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 16 --random-tokens 16 --strategy frequency --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_24_24_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 24 --random-tokens 24 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_16_16_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 16 --random-tokens 16 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_24_8_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 24 --random-tokens 8 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''    

# batch_t_c_b_Identity_m_128_s_128_p_4_k_8_24_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 8 --random-tokens 24 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_2_30_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 2 --random-tokens 30 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_30_2_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 30 --random-tokens 2 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_8_8_frequency
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 8 --random-tokens 8 --strategy frequency --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_8_8_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 8 --random-tokens 8 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_12_4_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 12 --random-tokens 4 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_4_12_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 4 --random-tokens 12 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_2_14_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 2 --random-tokens 14 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_4_4_frequency
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 4 --random-tokens 4 --strategy frequency --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_4_4_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 4 --random-tokens 4 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_6_2_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 6 --random-tokens 2 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_128_p_4_k_2_6_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 128 --patch 4\
    --tokens 2 --random-tokens 6 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_8_p_4_k_16_16_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 8 --patch 4\
    --tokens 16 --random-tokens 16 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# batch_t_c_b_Identity_m_128_s_32_p_4_k_4_4_ranking
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_batch_vit_b_16 --fit-type 'c' --basis Identity --modes 128 --sensors 32 --patch 4\
    --tokens 4 --random-tokens 4 --strategy ranking --epochs 100 --batch-size 128 --opt adamw --lr 0.003 --wd 0.3\
    --lr-scheduler cosineannealinglr --lr-warmup-method linear --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp\
    --label-smoothing 0.11 --clip-grad-norm 1 --device cuda --print-freq 100 --log-freq 10 --output-dir ''
