#!/bin/bash

#SBATCH --job-name=CIFAR10
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gpus-per-node=2
#SBATCH --output=out/%j.out
#SBATCH --time=5:00:00

source /sw/languages/anaconda/anaconda.3.9.13-2022-torch-cuda-11.7.0/etc/profile.d/conda.sh
conda activate sparse-tokens

# random_k_32
#torchrun --nproc_per_node=2 train.py\
#    --model sparse_token_vit_b_16 --token-mask random_k_32 --epochs 100 --batch-size 128\
#    --opt adamw --lr 0.003 --wd 0.3 --lr-scheduler cosineannealinglr --lr-warmup-method linear\
#    --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp --label-smoothing 0.11 --clip-grad-norm 1\
#    --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# random_k_16
#torchrun --nproc_per_node=2 train.py\
#    --model sparse_token_vit_b_16 --token-mask random_k_16 --epochs 100 --batch-size 128\
#    --opt adamw --lr 0.003 --wd 0.3 --lr-scheduler cosineannealinglr --lr-warmup-method linear\
#    --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp --label-smoothing 0.11 --clip-grad-norm 1\
#    --device cuda --print-freq 100 --log-freq 10 --output-dir ''

# random_k_8
torchrun --nproc_per_node=2 train.py\
    --model sparse_token_vit_b_16 --token-mask random_k_8 --epochs 100 --batch-size 128\
    --opt adamw --lr 0.003 --dropout 0.1 --attention-dropout 0.1 --wd 0.3 --lr-scheduler cosineannealinglr --lr-warmup-method linear\
    --lr-warmup-epochs 30 --lr-warmup-decay 0.033 --amp --label-smoothing 0.11 --clip-grad-norm 1\
    --device cuda --print-freq 100 --log-freq 10 --output-dir ''
